 # **Artificial Intelligence and Machine Learning : Worksheet-0**

 Prepared By: Aayush Khatiwada  
 Group: L6CG13

# **1. Exercise on Functions:**

## Task - 1.1:

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.



In [1]:
def unit_converter():
    """
    Prompts the user to select a unit conversion type and input a value.
    Performs the selected conversion and displays the result.

    Conversion Options:
    1 - Meters to Feet
    2 - Feet to Meters
    3 - Kilograms to Pounds
    4 - Pounds to Kilograms
    5 - Liters to Gallons
    6 - Gallons to Liters

    Returns:
    None
    """

    print("Unit Conversion Program")
    print("-----------------------")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Enter your choice (1-6): "))
        value = float(input("Enter the value to convert: "))

        if choice == 1:
            result = value * 3.28084
            print(f"{value} meters = {result:.4f} feet")

        elif choice == 2:
            result = value / 3.28084
            print(f"{value} feet = {result:.4f} meters")

        elif choice == 3:
            result = value * 2.20462
            print(f"{value} kilograms = {result:.4f} pounds")

        elif choice == 4:
            result = value / 2.20462
            print(f"{value} pounds = {result:.4f} kilograms")

        elif choice == 5:
            result = value * 0.264172
            print(f"{value} liters = {result:.4f} gallons")

        elif choice == 6:
            result = value / 0.264172
            print(f"{value} gallons = {result:.4f} liters")

        else:
            print("Error: Unsupported conversion type.")

    except ValueError:
        print("Error: Please enter valid numeric input.")


unit_converter()

Unit Conversion Program
-----------------------
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 3
Enter the value to convert: 60
60.0 kilograms = 132.2772 pounds


## Task - 1.2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [2]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum number in the list.
    """
    return min(numbers)


print("Mathematical Operations Program")
print("------------------------------")
print("1. Find Sum")
print("2. Find Average")
print("3. Find Maximum")
print("4. Find Minimum")

try:
    choice = int(input("Enter your choice (1-4): "))
    user_input = input("Enter numbers separated by spaces: ")
    numbers = list(map(float, user_input.split()))

    if not numbers:
        raise ValueError("List cannot be empty.")

    if choice == 1:
        print("Sum:", find_sum(numbers))
    elif choice == 2:
        print("Average:", find_average(numbers))
    elif choice == 3:
        print("Maximum:", find_maximum(numbers))
    elif choice == 4:
        print("Minimum:", find_minimum(numbers))
    else:
        print("Error: Invalid operation selected.")

except ValueError:
    print("Error: Please enter valid numeric values and make sure the list is not empty.")

Mathematical Operations Program
------------------------------
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter your choice (1-4): 2
Enter numbers separated by spaces: 88 83 60 70 50
Average: 70.2


# **2. Exercise on List Manipulation:**

## 2.1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

In [3]:
def extract_every_other(lst):
  return lst[::2]
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
result = extract_every_other(numbers)
print(result)

[1, 3, 5, 7, 9]


## 2.2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

In [4]:
def get_sublist(lst, start_index, end_index):
    return lst[start_index:end_index + 1]

numbers = [1,2,3,4,5,6]
result = get_sublist(numbers, 2, 4)
print(result)

[3, 4, 5]


## 2.3.Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

In [5]:
def reverse_list(lst):
  return lst [::-1]
numbers = [1,2,3,4,5]
result = reverse_list(numbers)
print(result)

[5, 4, 3, 2, 1]


## 2.4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting sublist.


In [6]:
def remove_first_last(lst):
  return lst[1:-1]
numbers = [1,2,3,4,5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]



## 2.5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.



In [7]:
def get_first_n(lst,n):
  return lst[:n]
numbers = [1,2,3,4,5]
result = get_first_n(numbers,3)
print(result)

[1, 2, 3]


## 2.6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.



In [8]:
def get_last_n(lst,n):
  return lst[-n:]
numbers = [1, 2, 3, 4, 5]
print(get_last_n(numbers, 2))

[4, 5]


## 2.7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

In [9]:
def reverse_skip(lst):

    return lst[-2::-2]


numbers = [1, 2, 3, 4, 5, 6]
print(reverse_skip(numbers))

[5, 3, 1]


#**3. Exercise on Nested List:**

## 3.1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.





In [10]:
def flatten(lst):

    flat = []
    for sublist in lst:
        for item in sublist:
            flat.append(item)
    return flat

nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))

[1, 2, 3, 4, 5]


## 3.2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.



In [11]:
def access_nested_element(lst, indices):

    element = lst
    for index in indices:
        element = element[index]
    return element

nested_list = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(nested_list, [1,2]))

6


## 3.3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).



In [12]:
def sum_nested(lst):

    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))

21


## 3.4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.


In [13]:
def remove_element(lst, elem):

    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

nested_list = [[1, 2], [3, 2], [4, 5]]
print(remove_element(nested_list, 2))

[[1], [3], [4, 5]]


## 3.5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).



In [14]:
def find_max(lst):

    maximum = float('-inf')
    for item in lst:
        if isinstance(item, list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum, item)
    return maximum

nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))

6


## 3.6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.



In [15]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


nested_list = [[1, 2], [2, 3], [2, 4]]
print(count_occurrences(nested_list, 2))

3


## 3.7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.



In [16]:
def deep_flatten(lst):

    flat = []
    for item in lst:
        if isinstance(item, list):
            flat.extend(deep_flatten(item))
        else:
            flat.append(item)
    return flat


nested_list = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(deep_flatten(nested_list))

[1, 2, 3, 4, 5, 6, 7, 8]


## 3.8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

In [17]:
def average_nested(lst):

    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list)
nested_list = [[1,2],[3,4],[5,6]]
print(average_nested(nested_list))

3.5


# **4. Exercises on Numpy**

## **4.1 Basic Vector and Matrix Operation with Numpy.**

### Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}


In [18]:
import numpy as np

# 1 Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array 2x2:")
print(empty_array)
print()

# 2️ Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("2. All Ones Array 4x2:")
print(ones_array)
print()

# 3️ Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), fill_value=7, dtype=int)
print("3. Full Array 3x3 filled with 7:")
print(fill_value_array)
print()

# 4️ Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("4. Zeros like given array:")
print(zeros_like_array)
print()

# 5️ Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("5. Ones like given array:")
print(ones_like_array)
print()

# 6️ Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("6. List converted to NumPy array:")
print(numpy_array)

1. Empty Array 2x2:
[[2.10272074e-315 0.00000000e+000]
 [6.81426337e-310 6.81426339e-310]]

2. All Ones Array 4x2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full Array 3x3 filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like given array:
[[0 0 0]
 [0 0 0]]

5. Ones like given array:
[[1 1 1]
 [1 1 1]]

6. List converted to NumPy array:
[1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [19]:
import numpy as np

# 1️ Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:")
print(arr1)
print()

# 2️ Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("2. 3x3 Matrix 0 to 8:")
print(matrix_3x3)
print()

# 3 Create a 3x3 identity matrix
identity_3x3 = np.eye(3)
print("3. 3x3 Identity Matrix:")
print(identity_3x3)
print()

# 4️ Create a random array of size 30 and find mean
rand_array_30 = np.random.random(30)
mean_val = rand_array_30.mean()
print("4. Random Array of size 30:")
print(rand_array_30)
print("Mean:", mean_val)
print()

# 5️ Create a 10x10 array with random values and find min and max
rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("5. 10x10 Random Array:")
print(rand_10x10)
print("Minimum:", min_val)
print("Maximum:", max_val)
print()

# 6️ Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # index 4 is the 5th element
print("6. Zero array with 5th element as 1:")
print(zero_array)
print()

# 7️ Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("7. Reversed array:")
print(reversed_arr)
print()

# 8️ Create a 2D array with 1 on border and 0 inside
n = 5  # size 5x5 example
border_array = np.ones((n, n))
border_array[1:-1, 1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:")
print(border_array)
print()

# 9️ Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 Checkerboard Pattern:")
print(checkerboard)

1. Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array of size 30:
[0.79999618 0.96090573 0.0385318  0.62050642 0.29115473 0.0248679
 0.26077652 0.91320083 0.64874934 0.57954317 0.72740601 0.23070695
 0.12323121 0.80975121 0.00170766 0.81723956 0.49343025 0.28872239
 0.79349734 0.66815243 0.80985941 0.91579834 0.01720344 0.73668435
 0.32669039 0.85756313 0.44114983 0.97604729 0.57269162 0.82257027]
Mean: 0.5522778569564092

5. 10x10 Random Array:
[[0.70925207 0.77782441 0.87729221 0.1519526  0.57157339 0.08153146
  0.94369199 0.63909371 0.28606696 0.69431   ]
 [0.8269599  0.8273937  0.61758849 0.0219016  0.61645583 0.04216312
  0.38357875 0.31948683 0.12533907 0.92630474]
 [0.28024467 0.42266128 0.86124306 0.6324936  0.1334056  0.70465847
  0.30885846 0.35516311 0.035

### Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


In [20]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x:\n", x)
print("y:\n", y)
print("v:", v)
print("w:", w)
print("\n")

# 1️ Add the two arrays
add_xy = x + y
print("1. x + y:\n", add_xy)
print()

# 2️ Subtract the two arrays
sub_xy = x - y
print("2. x - y:\n", sub_xy)
print()

# 3️ Multiply the array with an integer
mul_x = x * 3  # multiplying x by 3
print("3. x * 3:\n", mul_x)
print()

# 4️ Square of each element
square_x = x**2
print("4. x squared:\n", square_x)
print()

# 5️ Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("5. Dot products:")
print("v . w =", dot_vw)
print("x . v =\n", dot_xv)
print("x . y =\n", dot_xy)
print()

# 6️ Concatenate
concat_row_xy = np.concatenate((x, y), axis=0)  # along row
concat_col_vw = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)  # along column
print("6. Concatenation:")
print("Concatenate x and y along row:\n", concat_row_xy)
print("Concatenate v and w along column:\n", concat_col_vw)
print()

# 7️ Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("7. Attempt to concatenate x and v along rows results in error:")
    print("Error:", e)
    print("Explanation: x is 2x2 and v is 1x2 (different number of rows), cannot concatenate along axis=0.")

x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v: [ 9 10]
w: [11 12]


1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 3:
 [[ 3  6]
 [ 9 15]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v . w = 219
x . v =
 [29 77]
x . y =
 [[19 22]
 [50 58]]

6. Concatenation:
Concatenate x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]

7. Attempt to concatenate x and v along rows results in error:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2x2 and v is 1x2 (different number of rows), cannot concatenate along axis=0.


### Problem - 4: Matrix Operations:
• For the following arrays:

  A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT .

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [21]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("A:\n", A)
print("B:\n", B)
print("\n")

# 1️ Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A * A^-1 = I ?")
print(identity)
print("Check close to identity:", np.allclose(identity, np.eye(2)))  # True if close
print("\n")

# 2️ Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB =\n", AB)
print("   BA =\n", BA)
print("Check AB == BA:", np.allclose(AB, BA))  # False, so AB != BA
print("\n")

# 3️ Prove (AB)^T = B^T * A^T
AB_T = AB.T
B_TA_T = np.dot(B.T, A.T)
print("3. (AB)^T =\n", AB_T)
print("   B^T * A^T =\n", B_TA_T)
print("Check equality:", np.allclose(AB_T, B_TA_T))
print("\n")


# Represent in matrix form AX = B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Using np.linalg.inv
A_eq_inv = np.linalg.inv(A_eq)
X = np.dot(A_eq_inv, B_eq)
print("Solution using inverse method:")
print("x, y, z =", X)

# 3. Alternative: Using np.linalg.solve

X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve (recommended):")
print("x, y, z =", X_solve)

A:
 [[3 4]
 [7 8]]
B:
 [[5 3]
 [2 1]]


1. A * A^-1 = I ?
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Check close to identity: True


2. AB =
 [[23 13]
 [51 29]]
   BA =
 [[36 44]
 [13 16]]
Check AB == BA: False


3. (AB)^T =
 [[23 51]
 [13 29]]
   B^T * A^T =
 [[23 51]
 [13 29]]
Check equality: True


Solution using inverse method:
x, y, z = [ 2.  1. -2.]
Solution using np.linalg.solve (recommended):
x, y, z = [ 2.  1. -2.]


## **4.2 Experiment: How fast is Numpy?**

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
______________________________________________________________________


2. Element-wise Multiplication:

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
______________________________________________________________________

3. Dot Product:

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
______________________________________________________________________

4. Matrix Multiplication:

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [22]:
import numpy as np
import time

# 1. Element-wise Addition

size = 1_000_000

# Using Python lists
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Python list addition time: {end_time - start_time:.5f} seconds")

# Using NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
arr_add = arr1 + arr2
end_time = time.time()
print(f"NumPy array addition time: {end_time - start_time:.5f} seconds\n")

# 2. Element-wise Multiplication
# Python lists
start_time = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Python list multiplication time: {end_time - start_time:.5f} seconds")

# NumPy arrays
start_time = time.time()
arr_mul = arr1 * arr2
end_time = time.time()
print(f"NumPy array multiplication time: {end_time - start_time:.5f} seconds\n")

# 3. Dot Product
# Python lists
start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Python list dot product time: {end_time - start_time:.5f} seconds")

# NumPy arrays
start_time = time.time()
dot_arr = np.dot(arr1, arr2)
end_time = time.time()
print(f"NumPy array dot product time: {end_time - start_time:.5f} seconds\n")

# 4. Matrix Multiplication (1000x1000)

mat_size = 1000

# Python lists
mat1 = [[i + j for j in range(mat_size)] for i in range(mat_size)]
mat2 = [[i - j for j in range(mat_size)] for i in range(mat_size)]

start_time = time.time()
# Manual matrix multiplication
result = [[sum(mat1[i][k] * mat2[k][j] for k in range(mat_size)) for j in range(mat_size)] for i in range(mat_size)]
end_time = time.time()
print(f"Python list matrix multiplication time: {end_time - start_time:.5f} seconds")

# NumPy arrays
np_mat1 = np.arange(mat_size*mat_size).reshape(mat_size, mat_size)
np_mat2 = np.arange(mat_size*mat_size).reshape(mat_size, mat_size)

start_time = time.time()
np_result = np.dot(np_mat1, np_mat2)
end_time = time.time()
print(f"NumPy array matrix multiplication time: {end_time - start_time:.5f} seconds")

Python list addition time: 0.11836 seconds
NumPy array addition time: 0.00535 seconds

Python list multiplication time: 0.11925 seconds
NumPy array multiplication time: 0.00493 seconds

Python list dot product time: 0.10115 seconds
NumPy array dot product time: 0.00208 seconds

Python list matrix multiplication time: 182.80492 seconds
NumPy array matrix multiplication time: 1.56781 seconds
